Output: 
  output_folder:  ~/faunanet_data
  runtime: 9 # for security: a run with default should not run forever
  # run_until: 2024-04-04_12:05:24  # format: "%Y-%m-%d_%H:%M:%S"
  dump_config: True
  data_folder_suffix: ""
Recording:
  sample_rate: 48000
  length_s: 3
  channels: 1

